name: makaiapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  paginate_firestore: ^1.0.3
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.1.0
  firebase_core_platform_interface: 4.5.1
  cloud_firestore_platform_interface: any
  # firebase_auth_platform_interface: any
  firebase_dynamic_links: ^4.3.3
  firebase_storage: ^10.3.0
  cloud_functions: ^3.3.0
  firebase_messaging: ^13.0.4
  firebase_core: ^1.10.2
  flutter_local_notifications: ^16.1.0
  flutter_rating_bar: ^4.0.1
  location: ^5.0.3
  intro_slider: ^4.2.1
  shared_preferences: ^2.2.2
  smooth_star_rating_null_safety: ^1.0.4+2
  image_cropper: ^4.0.0
  image_picker: ^1.0.4
  rating_dialog: ^2.0.4
  google_maps_flutter: ^2.2.0
  in_app_review: ^2.0.8
  flutter_stripe: ^9.5.0+1
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  font_awesome_flutter: ^10.6.0
  pin_input_text_field: ^4.5.1
  cached_network_image: ^3.3.0
  uuid: ^3.0.5
  timeago: ^3.3.0
  url_launcher: ^6.2.1
  intl: ^0.17.0
  flutter_launcher_icons: ^0.13.1
  nanoid: ^1.0.0
  flutter_linkify: ^6.0.0
  permission_handler: ^11.0.1
  date_time_picker: ^2.1.0
  store_launcher_nullsafe: ^1.0.0
  share: ^2.0.4 # Verify if a new version is available or if the package is discontinued.
  step_progress_indicator: ^1.0.2
  flutter_datetime_picker: 1.5.1
  photo_view: ^0.14.0
  place_picker: ^0.10.0
  table_calendar: ^3.0.8
  awesome_notifications: 0.7.4+1
  geolocator: ^9.0.1
  geocoding: ^2.1.1
  dropdown_search: ^5.0.6
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  algolia: ^1.1.2
  flutter_phoenix: ^1.1.1
  smooth_page_indicator: ^1.1.0
  loading_indicator: ^3.1.1
  flutter_credit_card: ^4.0.1
  flutter_emoji: ^2.5.1
  passbase_flutter: ^3.2.1
  firebase_crashlytics: ^2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  firebase_core: ^2.14.0
  cloud_firestore: ^4.5.0
  firebase_core_web: ^2.3.0
  firebase_auth: ^4.10.0
  # cloud_firestore: ^4.2.0
  # cloud_firestore_platform_interface: ^5.11.4
  firebase_core_platform_interface: ^4.8.0
  
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Font2
      fonts:
        - asset: assets/fonts/nunitofont.ttf
